"""Pattern lists for rule-based guardrail checks."""

from __future__ import annotations

INJECTION_PATTERNS: list[str] = [
    "ignore previous instructions",
    "ignore all previous",
    "disregard your system prompt",
    "disregard previous instructions",
    "you are now",
    "act as if",
    "pretend you are",
    "forget your instructions",
    "override your",
    "new instructions:",
    "system prompt override",
    "jailbreak mode",
]

CONTENT_SAFETY_PATTERNS: list[str] = [
    "how to kill",
    "build a bomb",
    "make a weapon",
    "racial slur",
    "hate speech against",
    "commit suicide",
    "self-harm methods",
    "how to launder money",
    "buy illegal drugs",
    "instructions for hacking bank",
]

STOPWORDS: set[str] = {
    "a",
    "an",
    "and",
    "are",
    "as",
    "at",
    "be",
    "but",
    "by",
    "for",
    "from",
    "has",
    "he",
    "her",
    "his",
    "in",
    "is",
    "it",
    "its",
    "of",
    "on",
    "or",
    "she",
    "that",
    "the",
    "their",
    "this",
    "to",
    "was",
    "were",
    "will",
    "with",
    "you",
    "your",
    "not",
    "can",
    "have",
    "had",
}
